# Generated by Django 6.0.5 on 2026-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0009_stagegradingconfig_rubrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedeliverable',
            name='vault_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for vault filename. Variables: {year}, {course}, {project}, {stage}, {deliverable}, {semester}', max_length=255),
        ),
    ]
