# Generated by Django 6.0.5 on 2026-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0010_stagedeliverable_vault_file_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventgradingconfig',
            name='vault_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for vault filename. Variables: {year}, {course}, {project}, {event}, {semester}', max_length=255),
        ),
    ]
