# Generated by Django 6.0.5 on 2026-06-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0011_piteventgradingconfig_vault_file_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitEventDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_id', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=180)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('vault_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pit_event_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='defense.piteventgradingconfig')),
            ],
            options={
                'db_table': 'defense_scheduler_piteventdeliverable',
                'ordering': ['display_order', 'deliverable_id'],
                'constraints': [models.UniqueConstraint(fields=('pit_event_config', 'deliverable_id'), name='unique_deliverable_per_pit_event')],
            },
        ),
    ]
