# Generated by Django 6.0.5 on 2026-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0012_piteventdeliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventdeliverable',
            name='deliverable_type',
            field=models.CharField(choices=[('pre', 'Pre-Defense'), ('vault', 'Vault')], default='pre', max_length=20),
        ),
        migrations.AddField(
            model_name='piteventdeliverable',
            name='vault_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for vault filename. Variables: {year}, {course}, {project}, {event}, {semester}', max_length=255),
        ),
    ]
