# Generated by Django 6.0.5 on 2026-06-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0013_piteventdeliverable_deliverable_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventdeliverable',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If checked, this post-defense deliverable will be hidden from the public Digital Vault.'),
        ),
        migrations.AddField(
            model_name='stagedeliverable',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If checked, this post-defense deliverable will be hidden from the public Digital Vault.'),
        ),
    ]
