# Generated by Django 6.0.5 on 2026-06-27 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0014_piteventdeliverable_is_restricted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseschedule',
            name='documenter',
            field=models.ForeignKey(blank=True, help_text='Faculty assigned as documenter for this capstone defense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenter_defense_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
