# Generated by Django 6.0.5 on 2026-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0015_defenseschedule_documenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepanelist',
            name='is_chair',
            field=models.BooleanField(default=False),
        ),
    ]
