# Generated by Django 6.0.5 on 2026-06-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0016_schedulepanelist_is_chair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('project_title', models.CharField(max_length=255)),
                ('adviser_name', models.CharField(max_length=160)),
                ('defense_stage_label', models.CharField(max_length=120)),
                ('defense_date', models.DateField()),
                ('defense_time', models.TimeField()),
                ('room', models.CharField(max_length=120)),
                ('documenter_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('adviser_signed', 'Adviser Signed'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('documenter_signed_at', models.DateTimeField(blank=True, null=True)),
                ('adviser_signed_at', models.DateTimeField(blank=True, null=True)),
                ('chairman_signed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='defense_minutes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_signed_as_adviser', to=settings.AUTH_USER_MODEL)),
                ('chairman_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_signed_as_chairman', to=settings.AUTH_USER_MODEL)),
                ('documenter_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_signed_as_documenter', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='defense.defenseschedule')),
            ],
            options={
                'db_table': 'defense_minutes_defenseminutes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinutesPanelistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelist_name_snapshot', models.CharField(max_length=160)),
                ('panelist_role_snapshot', models.CharField(blank=True, max_length=40)),
                ('comments', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelist_comments', to='defense.defenseminutes')),
                ('panelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_comments_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'defense_minutes_minutespanelistcomment',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
