# Generated by Django 6.0.5 on 2026-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0017_defenseminutes_minutespanelistcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piteventdeliverable',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If checked, this post-defense deliverable will be hidden from the public Project Repository.'),
        ),
        migrations.AlterField(
            model_name='stagedeliverable',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='If checked, this post-defense deliverable will be hidden from the public Project Repository.'),
        ),
    ]
