# Generated by Django 6.0.5 on 2026-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0018_alter_piteventdeliverable_is_restricted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piteventdeliverable',
            old_name='vault_note',
            new_name='archive_note',
        ),
        migrations.RenameField(
            model_name='stagedeliverable',
            old_name='vault_note',
            new_name='archive_note',
        ),
        migrations.RenameField(
            model_name='piteventdeliverable',
            old_name='vault_file_template',
            new_name='archive_file_template',
        ),
        migrations.RenameField(
            model_name='piteventgradingconfig',
            old_name='vault_file_template',
            new_name='archive_file_template',
        ),
        migrations.RenameField(
            model_name='stagedeliverable',
            old_name='vault_file_template',
            new_name='archive_file_template',
        ),
        migrations.AlterField(
            model_name='piteventdeliverable',
            name='deliverable_type',
            field=models.CharField(choices=[('pre', 'Pre-Defense'), ('post', 'Post-Defense')], default='pre', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagedeliverable',
            name='deliverable_type',
            field=models.CharField(choices=[('pre', 'Pre-Defense'), ('post', 'Post-Defense')], default='pre', max_length=20),
        ),
    ]
