# Generated by Django 6.0.5 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0019_rename_vault_note_piteventdeliverable_archive_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piteventdeliverable',
            name='archive_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for archive filename. Variables: {year}, {course}, {project}, {event}, {semester}', max_length=255),
        ),
        migrations.AlterField(
            model_name='piteventgradingconfig',
            name='archive_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for archive filename. Variables: {year}, {course}, {project}, {event}, {semester}', max_length=255),
        ),
        migrations.AlterField(
            model_name='stagedeliverable',
            name='archive_file_template',
            field=models.CharField(blank=True, default='', help_text='Template for archive filename. Variables: {year}, {course}, {project}, {stage}, {deliverable}, {semester}', max_length=255),
        ),
    ]
