# Generated by Django 6.0.5 on 2026-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0020_alter_piteventdeliverable_archive_file_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventgradingconfig',
            name='event_code',
            field=models.SlugField(blank=True, default='', max_length=140),
        ),
    ]
