# Generated by Django 6.0.5 on 2026-07-31 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0021_piteventgradingconfig_event_code'),
        ('grading', '0012_teamgrade_adviser_score_is_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piteventgradingconfig',
            name='panel_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pit_event_configs_as_panel', to='grading.rubric'),
        ),
        migrations.AlterField(
            model_name='piteventgradingconfig',
            name='peer_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pit_event_configs_as_peer', to='grading.rubric'),
        ),
    ]
