# Generated by Antigravity on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0022_alter_piteventgradingconfig_panel_rubric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensestage',
            name='is_presentation_only',
            field=models.BooleanField(
                default=False,
                help_text='If true, this stage is an oral presentation, pitch, or demo day with no file uploads required.',
            ),
        ),
    ]
