# Generated by Django 6.0.5 on 2026-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0023_defensestage_is_presentation_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedeliverable',
            name='is_defense_material',
            field=models.BooleanField(default=True, help_text='If true, this pre-defense deliverable is visible to defense panelists during oral grading.'),
        ),
        migrations.AddField(
            model_name='stagedeliverable',
            name='verdict_condition',
            field=models.CharField(choices=[('all_pass', 'All Passing Defenses'), ('revisions_only', 'Revisions Verdict Only')], default='all_pass', help_text='Condition under which this post-defense deliverable is required.', max_length=20),
        ),
    ]
