# Generated by Django 6.0.5 on 2026-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0024_stagedeliverable_is_defense_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventdeliverable',
            name='file_format',
            field=models.CharField(blank=True, default='any', help_text='Allowed file format category for this deliverable.', max_length=30),
        ),
        migrations.AddField(
            model_name='stagedeliverable',
            name='file_format',
            field=models.CharField(blank=True, choices=[('any', 'Any File Format'), ('pdf', 'PDF Document (.pdf)'), ('video', 'Video (.mp4, .mov, .webm)'), ('image', 'Image / Poster (.png, .jpg, .svg)'), ('presentation', 'Presentation Slides (.pptx, .ppt, .pdf)'), ('document', 'Word / Document (.docx, .doc, .pdf)'), ('spreadsheet', 'Spreadsheet (.xlsx, .xls, .csv)'), ('archive', 'Archive / Source Code (.zip, .rar, .7z)'), ('audio', 'Audio Recording (.mp3, .wav, .aac)')], default='any', help_text='Allowed file format category for this deliverable.', max_length=30),
        ),
    ]
