# Generated by Django 6.0.5 on 2026-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0025_piteventdeliverable_file_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piteventdeliverable',
            name='is_defense_material',
            field=models.BooleanField(default=False, help_text='If true, this pre-defense deliverable is visible to defense panelists during oral grading.'),
        ),
        migrations.AlterField(
            model_name='stagedeliverable',
            name='is_defense_material',
            field=models.BooleanField(default=False, help_text='If true, this pre-defense deliverable is visible to defense panelists during oral grading.'),
        ),
    ]
