# Generated by Django 6.0.5 on 2026-10-04 05:40

import uuid
from django.db import migrations, models


def backfill_sessions(apps, schema_editor):
    Schedule = apps.get_model('defense', 'DefenseSchedule')
    Panel = apps.get_model('defense', 'SchedulePanelist')
    Invitation = apps.get_model('user_management', 'GuestPanelistCode')
    sessions = {}
    for schedule in Schedule.objects.order_by('pk').iterator():
        panels = tuple(Panel.objects.filter(schedule_id=schedule.pk).order_by('panelist_id').values_list('panelist_id', flat=True))
        guests = tuple(Invitation.objects.filter(schedules=schedule).order_by('evaluator_id').values_list('evaluator_id', flat=True))
        key = (schedule.semester_id, schedule.scope, schedule.defense_stage_id, schedule.event_name,
               str(schedule.scheduled_date), schedule.room, schedule.documenter_id, panels, guests)
        session_id = sessions.setdefault(key, uuid.uuid4())
        Schedule.objects.filter(pk=schedule.pk).update(session_id=session_id)


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0027_panelist_evaluation_draft'),
        ('user_management', '0009_guest_invitation_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseschedule',
            name='operation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='defenseschedule',
            name='operation_state',
            field=models.CharField(choices=[('normal', 'Normal'), ('paused', 'Interrupted'), ('postponed', 'Postponed'), ('no_show', 'No-show')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='defenseschedule',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='defenseschedule',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(backfill_sessions, migrations.RunPython.noop),
    ]
