# Generated by Django 6.0.5 on 2026-10-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0028_defenseschedule_operation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseMinutesRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='defense_minutes/')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='defense.defenseminutes')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
