# Generated by Django 6.0.5 on 2026-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0029_defenseminutesrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenseschedule',
            name='project_title_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='defenseschedule',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
