import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas

# System Branding Colors
MAROON = colors.HexColor('#7F1D1D')
MAROON_LIGHT = colors.HexColor('#991B1B')
GOLD = colors.HexColor('#D4A843')
TEXT_DARK = colors.HexColor('#1F2937')
TEXT_MUTED = colors.HexColor('#4B5563')
BG_LIGHT = colors.HexColor('#F9FAFB')
BORDER_GREY = colors.HexColor('#E5E7EB')
RED_WARNING_BG = colors.HexColor('#FEF2F2')
RED_WARNING_BORDER = colors.HexColor('#FCA5A5')
RED_WARNING_TEXT = colors.HexColor('#991B1B')


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw 'Page X of Y' 
    along with user attribution and timestamp footers on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        # Skip header and footer on the cover page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        
        # Header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(MAROON)
        self.drawString(54, 750, "DefenSYS Academic Management Portal")
        
        self.setStrokeColor(BORDER_GREY)
        self.setLineWidth(0.5)
        self.line(54, 742, 612 - 54, 742)
        
        # Footer
        doc = getattr(self, '_doctemplate', None)
        generated_by = getattr(doc, 'generated_by', 'System')
        generated_at = getattr(doc, 'generated_at', datetime.now().strftime('%Y-%m-%d %I:%M %p'))
        
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)
        self.drawString(54, 40, f"Generated by: {generated_by}  |  Date: {generated_at}")
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 40, page_str)
        
        self.line(54, 52, 612 - 54, 52)
        
        self.restoreState()


def defensys_styles():
    """
    Return custom stylesheet extensions for DefenSYS report layout.
    """
    styles = getSampleStyleSheet()
    
    # Custom styles definitions
    report_styles = {
        'ReportTitle': ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            textColor=MAROON,
            alignment=TA_CENTER,
            spaceAfter=15,
        ),
        'ReportSubtitle': ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            textColor=TEXT_MUTED,
            alignment=TA_CENTER,
            spaceAfter=25,
        ),
        'SectionHeader': ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            textColor=MAROON,
            spaceBefore=15,
            spaceAfter=8,
            keepWithNext=True,
        ),
        'SubSectionHeader': ParagraphStyle(
            'SubSectionHeader',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=11,
            textColor=TEXT_DARK,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        ),
        'BodyDark': ParagraphStyle(
            'BodyDark',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            textColor=TEXT_DARK,
            leading=13,
        ),
        'BodyDarkBold': ParagraphStyle(
            'BodyDarkBold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            textColor=TEXT_DARK,
            leading=13,
        ),
        'BodyMuted': ParagraphStyle(
            'BodyMuted',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            textColor=TEXT_MUTED,
            leading=12,
        ),
        'TableHeader': ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9.5,
            textColor=colors.whitesmoke,
        ),
        'TableCell': ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            textColor=TEXT_DARK,
            leading=12,
        ),
        'TableCellBold': ParagraphStyle(
            'TableCellBold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            textColor=TEXT_DARK,
            leading=12,
        ),
        'WarningText': ParagraphStyle(
            'WarningText',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            textColor=RED_WARNING_TEXT,
            alignment=TA_CENTER,
        ),
        'WarningSubtext': ParagraphStyle(
            'WarningSubtext',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            textColor=RED_WARNING_TEXT,
            alignment=TA_CENTER,
            spaceBefore=3,
        ),
    }
    
    for key, value in report_styles.items():
        if key not in styles:
            styles.add(value)
            
    return styles


def defensys_confidential_callout():
    """
    Renders a warning notice banner to display at the top of confidential documents.
    """
    styles = defensys_styles()
    
    content = [
        Paragraph("CONFIDENTIAL: INTERNAL ACADEMIC RECORD", styles['WarningText']),
        Paragraph("This document contains sensitive academic assessment data. Dissemination or reproduction is strictly restricted.", styles['WarningSubtext'])
    ]
    
    # Table containing the warning
    callout_table = Table([[content]], colWidths=[6.5*inch])
    callout_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), RED_WARNING_BG),
        ('BOX', (0, 0), (-1, -1), 1, RED_WARNING_BORDER),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 15),
        ('RIGHTPADDING', (0, 0), (-1, -1), 15),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return callout_table


def get_logo_element(width=1.2*inch, height=1.2*inch):
    """
    Safe loader for university logo. Returns an Image flowable if found, 
    otherwise returns a safe text-based placeholder to prevent generation crashes.
    """
    # Relative path from backend/modules/reports/ to frontend/assets/logo.png
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    logo_path = os.path.abspath(os.path.join(base_dir, '..', 'frontend', 'assets', 'logo.png'))
    
    if os.path.exists(logo_path):
        try:
            return Image(logo_path, width=width, height=height)
        except Exception:
            pass
            
    # Text-based fallback representing a shield emblem
    fallback_data = [["DEFENSYS"]]
    fallback_table = Table(fallback_data, colWidths=[width])
    fallback_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), MAROON),
        ('TEXTCOLOR', (0, 0), (-1, -1), GOLD),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
        ('TOPPADDING', (0, 0), (-1, -1), 20),
        ('BOX', (0, 0), (-1, -1), 2, GOLD),
    ]))
    return fallback_table


def defensys_cover_page(story, title, subtitle, generated_by_user, metadata_rows=None):
    """
    Common cover page layout with a university logo, maroon header bars,
    a metadata box, and accountability timestamps.
    """
    # Spacer to center the logo and title
    story.append(Spacer(1, 1.0*inch))
    
    # 1. Logo
    logo = get_logo_element(width=1.3*inch, height=1.3*inch)
    story.append(logo)
    story.append(Spacer(1, 0.4*inch))
    
    # 2. Main titles
    styles = defensys_styles()
    story.append(Paragraph(title.upper(), styles['ReportTitle']))
    if subtitle:
        story.append(Paragraph(subtitle, styles['ReportSubtitle']))
    
    # Ornamental Gold & Maroon bars
    bar_data = [['']]
    bar_table = Table(bar_data, colWidths=[7.0*inch])
    bar_table.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (-1, -1), 3, MAROON),
        ('LINEBELOW', (0, 0), (-1, -1), 1.5, GOLD),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(bar_table)
    story.append(Spacer(1, 0.5*inch))
    
    # 3. Metadata Table
    cover_data = []
    if metadata_rows:
        for label, val in metadata_rows:
            cover_data.append([Paragraph(f"<b>{label}</b>", styles['BodyDarkBold']), Paragraph(str(val), styles['BodyDark'])])
            
    # Add generation metadata
    cover_data.append([
        Paragraph("<b>Generated By:</b>", styles['BodyDarkBold']),
        Paragraph(generated_by_user, styles['BodyDark'])
    ])
    cover_data.append([
        Paragraph("<b>Date of Export:</b>", styles['BodyDarkBold']),
        Paragraph(datetime.now().strftime('%B %d, %Y at %I:%M %p'), styles['BodyDark'])
    ])
    
    meta_table = Table(cover_data, colWidths=[2.2*inch, 4.3*inch])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, BORDER_GREY),
    ]))
    story.append(meta_table)
    
    # End page
    story.append(PageBreak())


def defensys_table_style():
    """
    Standard tabular layout theme for DefenSYS grid lists.
    """
    return TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), MAROON),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_GREY),
    ])
