# Generated by Django 6.0.4 on 2026-04-24 08:56

import academic_period_management.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=9, unique=True, validators=[academic_period_management.models.validate_school_year_label])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-label'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic_period_management.schoolyear')),
            ],
            options={
                'ordering': ['school_year__label', 'id'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'label'), name='unique_semester_per_school_year'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_semester')],
            },
        ),
    ]
