# Generated by Django 6.0.5 on 2026-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period_management', '0002_semester_capstone_evaluation_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='capstone_adviser_grading_enabled',
            field=models.BooleanField(default=True, help_text='When off, advisers cannot submit adviser grades for Capstone teams.'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='capstone_peer_evaluation_enabled',
            field=models.BooleanField(default=True, help_text='When off, students cannot use peer evaluation for Capstone teams.'),
        ),
    ]
