# Generated by Django 6.0.4 on 2026-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='team_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='teamdocument',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
