# Generated by Django 6.0.4 on 2026-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_deliverables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablesubmission',
            name='file',
            field=models.FileField(blank=True, help_text='Actual uploaded file', null=True, upload_to='deliverables/%Y/%m/'),
        ),
    ]
