# Generated by Django 6.0.4 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_deliverables', '0003_deliverablesubmission_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablesubmission',
            name='category',
            field=models.CharField(blank=True, default='', help_text='ML-predicted technology category', max_length=100),
        ),
        migrations.AddField(
            model_name='deliverablesubmission',
            name='category_confidence',
            field=models.FloatField(blank=True, help_text='Classification confidence score (0-100)', null=True),
        ),
    ]
