"""
Django settings for defensys_backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# App packages live under backend/modules/; keep short names in INSTALLED_APPS.
_modules_dir = BASE_DIR / 'modules'
if _modules_dir.is_dir():
    _modules_path = str(_modules_dir.resolve())
    if _modules_path not in sys.path:
        sys.path.insert(0, _modules_path)


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name: str, default: str = '') -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'Missing DJANGO_SECRET_KEY (or SECRET_KEY). Copy backend/.env.example to backend/.env and set it.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = _env_list(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,192.168.1.5,192.168.1.20',
)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

_csrf_trusted = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in _csrf_trusted.split(',') if origin.strip()
]


# Optional production CORS allowlist for deployments where Flutter and API are
# served from different origins. Same-origin nginx deployments do not need this.
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ALLOWED_ORIGINS')

# Allow 192.168.* and 10.* origins during local development.
# Automatically disabled in production when DEBUG=False.
CORS_ALLOW_LAN = DEBUG

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'authentication_access_control',
    'dashboards',
    'academic_period_management',
    'user_management',
    'student_teams',
    'defense',
    'grading',
    'repository',
    'curriculum_analytics',
    'channels',
    'realtime',
    'reports',
    'notifications',
]

# App API tests only; do not collect ad-hoc scripts in backend/tests/ (see tests/README.md).
TEST_RUNNER = 'defensys_backend.test_runner.AppOnlyDiscoverRunner'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'defensys_backend.cors.LocalCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'defensys_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'defensys_backend.wsgi.application'
ASGI_APPLICATION = 'defensys_backend.asgi.application'

_use_inmemory_channels = 'test' in sys.argv or _env_bool(
    'DEFENSYS_USE_INMEMORY_CHANNELS',
    default=False,
)
if _use_inmemory_channels:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    _redis_url = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_redis_url],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'defensys_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': int(os.environ.get('DJANGO_DB_CONN_MAX_AGE', '0' if DEBUG else '600')),
        'CONN_HEALTH_CHECKS': True,
    }
}

if not DATABASES['default']['PASSWORD'] and not DEBUG:
    raise ImproperlyConfigured(
        'POSTGRES_PASSWORD is required when DJANGO_DEBUG is False.'
    )

_db_name = DATABASES['default']['NAME']
DATABASES['default']['TEST'] = {
    'NAME': f'test_{_db_name}',
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Institution timezone (Philippines Standard Time / PHT, UTC+8)
TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files) — bytes on disk or S3; metadata in PostgreSQL.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Upload limits (500MB total request size, 50MB maximum kept in memory before streaming to disk)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 500 * 1024 * 1024))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', 50 * 1024 * 1024))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': MEDIA_ROOT,
            'base_url': MEDIA_URL,
        },
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}


AUTH_USER_MODEL = 'authentication_access_control.User'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'defensys_backend.exception_handlers.defensys_exception_handler',
    'DEFAULT_THROTTLE_RATES': {
        'token_refresh': '10/min',
        'login': '5/min',
        'anon': '10/min',
        'logout': '5/min',
        'password_reset': '3/hour',
        'guest_code': '5/min',
    },
}

# JWT Settings
from datetime import timedelta


_JWT_ACCESS_HOURS = float(os.environ.get('JWT_ACCESS_TOKEN_HOURS', '8'))
_JWT_REFRESH_STANDARD_HOURS = float(os.environ.get('JWT_REFRESH_STANDARD_HOURS', '12'))
_JWT_REFRESH_REMEMBER_DAYS = float(os.environ.get('JWT_REFRESH_REMEMBER_DAYS', '7'))

SIMPLE_JWT_REFRESH_STANDARD = timedelta(hours=_JWT_REFRESH_STANDARD_HOURS)
SIMPLE_JWT_REFRESH_REMEMBER = timedelta(days=_JWT_REFRESH_REMEMBER_DAYS)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=_JWT_ACCESS_HOURS),
    'REFRESH_TOKEN_LIFETIME': SIMPLE_JWT_REFRESH_REMEMBER,
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Email Backend (Gmail SMTP)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', f'DefenSYS <{EMAIL_HOST_USER}>'
)

# Password reset token lifetime (seconds). Default: 1 hour.
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '3600'))

# Base URL shown in emails (no trailing slash).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8000').rstrip('/')


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'defensys.authz': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'student_teams.weekly_progress': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Error Tracking & APM Integration (Sentry)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(
                os.environ.get(
                    'SENTRY_TRACES_SAMPLE_RATE', '0.1' if not DEBUG else '1.0'
                )
            ),
            send_default_pii=False,
            environment=os.environ.get(
                'ENVIRONMENT', 'development' if DEBUG else 'production'
            ),
        )
    except ImportError:
        pass

