# Generated by Django 6.0.5 on 2026-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_studentrecord_section_pitinstructorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyroleassignment',
            name='role_key',
            field=models.CharField(choices=[('panelist', 'Defense Panelist'), ('pit_lead', 'PIT Lead'), ('adviser', 'Project Adviser'), ('documenter', 'Documenter')], max_length=32),
        ),
    ]
