# Generated by Django 6.0.5 on 2026-07-05 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period_management', '0005_semestertransitionlog'),
        ('user_management', '0005_update_role_choices_documenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year_level', 'section', 'faculty__last_name', 'faculty__first_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pitinstructorassignment',
            name='pit_instr_scope_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pitinstructorassignment',
            name='unique_pit_instructor_assignment',
        ),
        migrations.AddField(
            model_name='sectioninstructorassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_instructor_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectioninstructorassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_instructor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectioninstructorassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_instructor_assignments', to='academic_period_management.semester'),
        ),
        migrations.RemoveField(
            model_name='pitinstructorassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='pitinstructorassignment',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='pitinstructorassignment',
            name='semester',
        ),
        migrations.AddIndex(
            model_name='sectioninstructorassignment',
            index=models.Index(fields=['semester', 'year_level', 'section', 'is_active'], name='sect_instr_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectioninstructorassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'semester', 'year_level', 'section'), name='unique_section_instructor_assignment'),
        ),
        migrations.DeleteModel(
            name='PitInstructorAssignment',
        ),
    ]
