# Generated by Django 6.0.5 on 2026-10-03 06:05

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def link_existing_defenses(apps, schema_editor):
    Code = apps.get_model('user_management', 'GuestPanelistCode')
    through = Code.schedules.through
    through.objects.using(schema_editor.connection.alias).bulk_create([
        through(guestpanelistcode_id=pk, defenseschedule_id=schedule_id)
        for pk, schedule_id in Code.objects.using(schema_editor.connection.alias).values_list('pk', 'defense_schedule_id')
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0027_panelist_evaluation_draft'),
        ('user_management', '0007_panelist_eligibility_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpanelistcode',
            name='access_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guestpanelistcode',
            name='last_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestpanelistcode',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='guest_invitations', to='defense.defenseschedule'),
        ),
        migrations.CreateModel(
            name='ExternalEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('pit_year', models.CharField(blank=True, max_length=50)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_evaluators_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_evaluators_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='guestpanelistcode',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='user_management.externalevaluator'),
        ),
        migrations.AddConstraint(
            model_name='externalevaluator',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_external_evaluator_email'),
        ),
        migrations.RunPython(link_existing_defenses, migrations.RunPython.noop),
    ]
