# Generated by Django 6.0.5 on 2026-10-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0027_panelist_evaluation_draft'),
        ('user_management', '0008_external_evaluator_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestpanelistcode',
            name='defense_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_panelist_codes', to='defense.defenseschedule'),
        ),
    ]
