# Generated by Django 6.0.4 on 2026-04-25 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_period_management', '0001_initial'),
        ('defense_scheduler', '0001_initial'),
        ('rubric_engine', '0001_initial'),
        ('student_teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('capstone', 'Capstone'), ('pit', 'PIT')], default='capstone', max_length=20)),
                ('stage_label', models.CharField(default='Unscheduled', max_length=120)),
                ('panel_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adviser_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panel_weight', models.PositiveSmallIntegerField(default=50)),
                ('adviser_weight', models.PositiveSmallIntegerField(default=30)),
                ('peer_weight', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_peers', 'Awaiting Peers'), ('published', 'Published')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_grade_records', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='defense_scheduler.defenseschedule')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='academic_period_management.semester')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='student_teams.studentteam')),
            ],
            options={
                'ordering': ['team__level', 'team__name', 'stage_label'],
            },
        ),
        migrations.CreateModel(
            name='StudentPeerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_grade_summaries', to=settings.AUTH_USER_MODEL)),
                ('team_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_member_grades', to='grade_center.teamgrade')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name', 'student__username'],
            },
        ),
        migrations.CreateModel(
            name='GradeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('panel', 'Panel'), ('adviser', 'Adviser'), ('peer', 'Peer')], max_length=20)),
                ('criterion_name', models.CharField(max_length=160)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('remarks', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_breakdowns', to='rubric_engine.rubric')),
                ('team_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='grade_center.teamgrade')),
            ],
            options={
                'ordering': ['evaluation_type', 'display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='teamgrade',
            index=models.Index(fields=['scope', 'status'], name='grade_cente_scope_8e8f63_idx'),
        ),
        migrations.AddIndex(
            model_name='teamgrade',
            index=models.Index(fields=['stage_label'], name='grade_cente_stage_l_1fb308_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamgrade',
            constraint=models.UniqueConstraint(fields=('team', 'semester', 'scope', 'stage_label'), name='unique_grade_record_per_team_context'),
        ),
        migrations.AddConstraint(
            model_name='studentpeergrade',
            constraint=models.UniqueConstraint(fields=('team_grade', 'student'), name='unique_peer_grade_per_student_grade_context'),
        ),
        migrations.AddIndex(
            model_name='gradebreakdown',
            index=models.Index(fields=['evaluation_type'], name='grade_cente_evaluat_389856_idx'),
        ),
    ]
