# Generated by Django 6.0.4 on 2026-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='file',
            field=models.FileField(blank=True, help_text='Actual uploaded file', null=True, upload_to='vault_entries/%Y/%m/'),
        ),
    ]
