# Generated by Django 6.0.4 on 2026-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_vault', '0002_vaultentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Full text extracted from PDF for ML search'),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Auto-generated summary of PDF content'),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted keywords/topics from PDF content'),
        ),
    ]
