# Generated by Django 6.0.5 on 2026-05-21 10:15

import repository.archive.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_vaultentry_ml_category_and_approved_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='file',
            field=models.FileField(blank=True, help_text='Actual uploaded file', null=True, upload_to=repository.archive.upload_paths.archive_entry_upload_to),
        ),
    ]
