# Generated by Django 6.0.5 on 2026-06-11 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_status_to_accepted(apps, schema_editor):
    DeliverableSubmission = apps.get_model('repository', 'DeliverableSubmission')
    DeliverableSubmission.objects.all().update(status='accepted')


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_vaultentry_stage_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablesubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Rejection feedback or remarks'),
        ),
        migrations.AddField(
            model_name='deliverablesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverablesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverablesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Review and approval status', max_length=20),
        ),
        migrations.RunPython(set_existing_status_to_accepted),
    ]
