# Generated by Django 6.0.5 on 2026-07-05 11:41

import django.db.models.deletion
import django.utils.timezone
import repository.archive.upload_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0019_rename_vault_note_piteventdeliverable_archive_note_and_more'),
        ('repository', '0008_deliverablesubmission_feedback_and_more'),
        ('student_teams', '0007_sectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename the VaultEntry model to ArchiveEntry
        migrations.RenameModel(
            old_name='VaultEntry',
            new_name='ArchiveEntry',
        ),
        # Rename the DB table from digital_vault_vaultentry to repository_archiveentry
        migrations.AlterModelTable(
            name='ArchiveEntry',
            table='repository_archiveentry',
        ),
        # Alter upload_to path for file field
        migrations.AlterField(
            model_name='archiveentry',
            name='file',
            field=models.FileField(blank=True, help_text='Actual uploaded file', null=True, upload_to=repository.archive.upload_paths.archive_entry_upload_to),
        ),
        # Alter deliverable_type choices on DeliverableSubmission
        migrations.AlterField(
            model_name='deliverablesubmission',
            name='deliverable_type',
            field=models.CharField(choices=[('pre', 'Pre-Defense'), ('post', 'Post-Defense')], max_length=20),
        ),
        # Remove old indexes and constraints
        migrations.RemoveIndex(
            model_name='archiveentry',
            name='vault_entry_type_team_idx',
        ),
        migrations.RemoveConstraint(
            model_name='archiveentry',
            name='unique_vault_entry_per_academic_year',
        ),
        # Add new indexes and constraints with renamed labels
        migrations.AddIndex(
            model_name='archiveentry',
            index=models.Index(fields=['entry_type', 'team'], name='archive_entry_type_team_idx'),
        ),
        migrations.AddConstraint(
            model_name='archiveentry',
            constraint=models.UniqueConstraint(fields=('entry_type', 'file_name', 'academic_year'), name='unique_archive_entry_per_academic_year'),
        ),
    ]
