# Generated by Django 6.0.5 on 2026-07-09 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0020_alter_piteventdeliverable_archive_file_template_and_more'),
        ('repository', '0009_archiveentry_and_more'),
        ('student_teams', '0007_sectionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveentry',
            name='defense_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_entries', to='defense.defensestage'),
        ),
        migrations.AlterField(
            model_name='archiveentry',
            name='pit_event_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_entries', to='defense.piteventgradingconfig'),
        ),
        migrations.AlterField(
            model_name='archiveentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_entries', to='student_teams.studentteam'),
        ),
        migrations.AlterField(
            model_name='archiveentry',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_archive_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
