# Generated by Django 6.0.5 on 2026-07-11 13:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_files(apps, schema_editor):
    DeliverableSubmission = apps.get_model('repository', 'DeliverableSubmission')
    DeliverableSubmissionFile = apps.get_model('repository', 'DeliverableSubmissionFile')
    
    for submission in DeliverableSubmission.objects.all():
        if submission.file:
            DeliverableSubmissionFile.objects.create(
                submission=submission,
                file=submission.file,
                file_name=submission.file_name or 'document.pdf',
                file_size=submission.file_size or '',
                extracted_text=submission.extracted_text or '',
                topics=submission.topics or [],
                summary=submission.summary or '',
                category=submission.category or '',
                category_confidence=submission.category_confidence,
                uploaded_at=submission.uploaded_at or submission.created_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_alter_archiveentry_defense_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverablesubmission',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverablesubmission',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='DeliverableSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Actual uploaded file', null=True, upload_to='deliverables/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=40)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Full text extracted from PDF for ML search')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Auto-extracted keywords/topics from PDF content')),
                ('summary', models.TextField(blank=True, default='', help_text='Auto-generated summary of PDF content')),
                ('category', models.CharField(blank=True, default='', help_text='ML-predicted technology category', max_length=100)),
                ('category_confidence', models.FloatField(blank=True, help_text='Classification confidence score (0-100)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repository.deliverablesubmission')),
            ],
            options={
                'db_table': 'capstone_deliverables_deliverablesubmissionfile',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RunPython(migrate_existing_files, reverse_code=migrations.RunPython.noop),
    ]
