# Generated by Django 6.0.5 on 2026-07-28 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_alter_deliverablesubmission_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('pit', 'PIT'), ('capstone', 'Capstone')], max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('classify', 'Classify'), ('override', 'Override Status'), ('demo_fill', 'Demo Fill')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=60)),
                ('new_status', models.CharField(blank=True, max_length=60)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_archive_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repository_archive_projectarchivelog',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='RepositoryAuditLog',
        ),
    ]
