# Generated by Django 6.0.5 on 2026-08-31 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_projectarchivelog_delete_repositoryauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(db_index=True, help_text='ID of the repository entry (e.g. capstone-1-2, pit-5, doc_3)', max_length=120)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, default='Student', max_length=50)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('remark', models.TextField(blank=True, default='', help_text='User review remarks or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repository_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_id'], name='repo_review_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_id', 'user'), name='unique_user_repository_review')],
            },
        ),
        migrations.CreateModel(
            name='UserBookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Currently Reading'), ('completed', 'Completed'), ('favorited', 'Favorited')], default='reading', max_length=30)),
                ('last_read_page', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookshelf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repository_bookshelf',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='repo_shelf_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_id'), name='unique_user_bookshelf_target')],
            },
        ),
    ]
