# Generated by Django 6.0.5 on 2026-10-05 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_repositoryreview_userbookshelf'),
        ('student_teams', '0008_studentteam_unlocked_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverablesubmission',
            name='unique_deliverable_submission_per_team_stage',
        ),
        migrations.AddField(
            model_name='archiveentry',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliverablesubmission',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='deliverablesubmission',
            constraint=models.UniqueConstraint(fields=('team', 'stage_label', 'deliverable_id', 'project_version'), name='unique_deliverable_submission_per_team_stage'),
        ),
    ]
