# Generated by Django 6.0.5 on 2026-10-05 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0030_defenseschedule_project_title_snapshot_and_more'),
        ('repository', '0014_remove_deliverablesubmission_unique_deliverable_submission_per_team_stage_and_more'),
        ('student_teams', '0009_teamrecoveryauthorization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archiveentry',
            name='unique_archive_entry_per_academic_year',
        ),
        migrations.AddConstraint(
            model_name='archiveentry',
            constraint=models.UniqueConstraint(fields=('entry_type', 'file_name', 'academic_year', 'project_version'), name='unique_archive_entry_per_academic_year'),
        ),
    ]
