# Generated by Django 6.0.5 on 2026-05-27 16:27

import authentication_access_control.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0004_systemauditlog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication_access_control.models.DefenSysUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='authenticat_created_29cb3e_idx',
            old_name='authenticat_created_36f139_idx',
        ),
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='authenticat_categor_8364bb_idx',
            old_name='authenticat_categor_bfa156_idx',
        ),
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='authenticat_actor_i_8d066a_idx',
            old_name='authenticat_actor_i_e84a45_idx',
        ),
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='authenticat_target__640abd_idx',
            old_name='authenticat_target__0f323c_idx',
        ),
    ]
