# Generated by Django 6.0.5 on 2026-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0005_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_documenter',
            field=models.BooleanField(default=False),
        ),
    ]
