# Generated by Django 6.0.5 on 2026-06-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0006_add_is_documenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_repo_assistant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='repo_assistant_year',
        ),
    ]
