# Generated by Django 6.0.5 on 2026-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0007_remove_user_is_repo_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, help_text='Uploaded e-signature image (PNG/JPG) for document signing.', null=True, upload_to='e_signatures/'),
        ),
    ]
