# Generated by Django 6.0.5 on 2026-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0008_user_e_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adviser_phase',
        ),
    ]
