# Generated by Django 6.0.5 on 2026-07-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0009_remove_user_adviser_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_id',
        ),
    ]
