# Generated by Django 6.0.5 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0010_remove_user_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='avatars/'),
        ),
    ]
