# Generated by Django 6.0.5 on 2026-08-22 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0011_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('reset_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'is_verified'], name='authenticat_user_id_123924_idx'), models.Index(fields=['reset_token'], name='authenticat_reset_t_13bd8e_idx'), models.Index(fields=['created_at'], name='authenticat_created_508b54_idx')],
            },
        ),
    ]
