# Generated by Django 6.0.5 on 2026-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0012_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='authenticat_user_id_123924_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='authenticat_created_508b54_idx',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_c23e34_idx'),
        ),
    ]
