# Generated by Django 6.0.5 on 2026-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0013_remove_passwordresetotp_authenticat_user_id_123924_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='category',
            field=models.CharField(choices=[('academic_period', 'Academic Periods'), ('grade_center', 'Grade Center'), ('scheduling', 'Scheduling'), ('student_teams', 'Student Teams'), ('repository', 'Repository'), ('guest_access', 'Guest Access'), ('user_management', 'User Management')], max_length=40),
        ),
    ]
