# Generated by Django 6.0.5 on 2026-08-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0014_alter_systemauditlog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="User's mobile phone number for SMS notifications.", max_length=32),
        ),
    ]
