# Generated by Django 6.0.5 on 2026-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_access_control', '0015_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='category',
            field=models.CharField(choices=[('academic_period', 'Academic Periods'), ('grade_center', 'Evaluation & Grades'), ('scheduling', 'Scheduling'), ('student_teams', 'Student Teams'), ('repository', 'Repository'), ('guest_access', 'Guest Access'), ('user_management', 'User Management')], max_length=40),
        ),
    ]
