# Generated by Django 6.0.4 on 2026-05-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_weekly_progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weeklyprogressreport',
            new_name='student_wee_student_059a10_idx',
            old_name='student_wee_student_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyprogressreport',
            new_name='student_wee_team_id_0cb02e_idx',
            old_name='student_wee_team_id_idx',
        ),
    ]
