# Generated by Django 6.0.4 on 2026-05-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_weekly_progress', '0002_add_file_upload'),
        ('student_weekly_progress', '0002_rename_student_wee_student_idx_student_wee_student_059a10_idx_and_more'),
    ]

    operations = [
    ]
