# Generated by Django 6.0.4 on 2026-05-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_weekly_progress', '0003_merge_20260508_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogressreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='weekly_reports/%Y/%m/'),
        ),
    ]
