# Generated by Django 6.0.4 on 2026-04-24 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_period_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project_title', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('1st Year PIT', '1st Year PIT'), ('2nd Year PIT', '2nd Year PIT'), ('3rd Year PIT', '3rd Year PIT'), ('3rd Year Capstone', '3rd Year Capstone'), ('4th Year Capstone', '4th Year Capstone')], max_length=30)),
                ('year_level', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Failed', 'Failed'), ('Delayed/Extended', 'Delayed/Extended')], default='Pending', max_length=30)),
                ('capstone_phase', models.CharField(blank=True, choices=[('active', 'active'), ('extended', 'extended')], max_length=20, null=True)),
                ('ready_for_stage', models.CharField(blank=True, max_length=80, null=True)),
                ('current_defense_stage', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_student_teams', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='academic_period_management.semester')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_teams.studentteam')),
            ],
            options={
                'ordering': ['order', 'student__username'],
            },
        ),
        migrations.AddField(
            model_name='studentteam',
            name='members',
            field=models.ManyToManyField(related_name='student_teams', through='student_teams.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'student'), name='unique_student_per_team'),
        ),
        migrations.AddConstraint(
            model_name='studentteam',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='unique_team_name_per_level'),
        ),
    ]
