# Generated by Django 6.0.5 on 2026-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_teams', '0007_sectionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteam',
            name='unlocked_stages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
