# Generated by Django 6.0.5 on 2026-10-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period_management', '0005_semestertransitionlog'),
        ('defense', '0030_defenseschedule_project_title_snapshot_and_more'),
        ('grading', '0017_remove_teamgrade_unique_capstone_grade_per_team_stage_and_more'),
        ('student_teams', '0008_studentteam_unlocked_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRecoveryAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_version', models.PositiveIntegerField()),
                ('previous_project_title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('retake', 'Another attempt'), ('new_concept', 'Replacement concept')], max_length=20)),
                ('reason', models.TextField()),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_project_version', models.PositiveIntegerField(blank=True, null=True)),
                ('replacement_project_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-authorized_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='teamstageprogress',
            name='unique_team_stage_progress',
        ),
        migrations.AddField(
            model_name='studentteam',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamstageprogress',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teamstageprogress',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('grading', 'Grading'), ('passed', 'Passed'), ('failed', 'Failed'), ('archived', 'Archived'), ('revisions_pending', 'Revision clearance pending'), ('for_redefense', 'For Re-defense')], default='locked', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teamstageprogress',
            constraint=models.UniqueConstraint(fields=('team', 'semester', 'defense_stage', 'project_version'), name='unique_team_stage_progress'),
        ),
        migrations.AddField(
            model_name='teamrecoveryauthorization',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamrecoveryauthorization',
            name='defense_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='defense.defensestage'),
        ),
        migrations.AddField(
            model_name='teamrecoveryauthorization',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_period_management.semester'),
        ),
        migrations.AddField(
            model_name='teamrecoveryauthorization',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_authorizations', to='student_teams.studentteam'),
        ),
    ]
