# Generated by Django 6.0.5 on 2026-05-28 02:57

from django.db import migrations

def migrate_ready_for_archive(apps, schema_editor):
    TeamGrade = apps.get_model('grading', 'TeamGrade')
    TeamGrade.objects.filter(status='ready_for_archive').update(status='published')

class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_panelist_grade_submissions'),
    ]

    operations = [
        migrations.RunPython(migrate_ready_for_archive, reverse_code=migrations.RunPython.noop),
    ]
