# Generated by Django 6.0.5 on 2026-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_remove_ready_for_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgrade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_peers', 'Awaiting Peers'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
