# Generated by Django 6.0.5 on 2026-06-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_peer_grades(apps, schema_editor):
    StudentPeerGrade = apps.get_model('grading', 'StudentPeerGrade')
    StudentStageGrade = apps.get_model('grading', 'StudentStageGrade')
    for spg in StudentPeerGrade.objects.all():
        peer_score = None
        if spg.max_score > 0:
            peer_score = (spg.average_score / spg.max_score) * 100
        StudentStageGrade.objects.create(
            team_grade=spg.team_grade,
            student=spg.student,
            peer_score=peer_score,
            final_grade=spg.team_grade.final_grade,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0014_piteventdeliverable_is_restricted_and_more'),
        ('grading', '0008_alter_teamgrade_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adviser_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grade_center_studentstagegrade',
                'ordering': ['student__last_name', 'student__first_name', 'student__username'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='studentpeergrade',
            name='unique_peer_grade_per_student_grade_context',
        ),
        migrations.RemoveConstraint(
            model_name='panelistgradesubmission',
            name='unique_panel_submission_per_panelist',
        ),
        migrations.RemoveConstraint(
            model_name='panelistgradesubmission',
            name='unique_panel_submission_per_guest',
        ),
        migrations.AddField(
            model_name='gradebreakdown',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_breakdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panelistgradesubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panelist_student_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubric',
            name='target_type',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual')], default='team', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='panelistgradesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('panelist__isnull', False), ('student__isnull', True)), fields=('team_grade', 'schedule', 'panelist'), name='unique_panel_submission_per_panelist'),
        ),
        migrations.AddConstraint(
            model_name='panelistgradesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('panelist__isnull', False), ('student__isnull', False)), fields=('team_grade', 'schedule', 'panelist', 'student'), name='unique_panel_submission_per_panelist_student'),
        ),
        migrations.AddConstraint(
            model_name='panelistgradesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_code_id__isnull', False), ('student__isnull', True)), fields=('team_grade', 'schedule', 'guest_code_id'), name='unique_panel_submission_per_guest'),
        ),
        migrations.AddConstraint(
            model_name='panelistgradesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_code_id__isnull', False), ('student__isnull', False)), fields=('team_grade', 'schedule', 'guest_code_id', 'student'), name='unique_panel_submission_per_guest_student'),
        ),
        migrations.AddField(
            model_name='studentstagegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_stage_grade_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentstagegrade',
            name='team_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grading.teamgrade'),
        ),
        migrations.RunPython(migrate_peer_grades),
        migrations.RemoveField(
            model_name='studentpeergrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentpeergrade',
            name='team_grade',
        ),
        migrations.AddConstraint(
            model_name='studentstagegrade',
            constraint=models.UniqueConstraint(fields=('team_grade', 'student'), name='unique_student_stage_grade'),
        ),
        migrations.DeleteModel(
            name='StudentPeerGrade',
        ),
    ]
