# Generated by Django 6.0.5 on 2026-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_force_peer_rubrics_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriterion',
            name='target_type',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual')], default='team', max_length=20),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='target_type',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual'), ('both', 'Both (Team & Individual)')], default='team', max_length=20),
        ),
    ]
