# Generated by Django 6.0.5 on 2026-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_rubriccriterion_target_type_alter_rubric_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgrade',
            name='adviser_score_is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='panel_score_is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='peer_score_is_override',
            field=models.BooleanField(default=False),
        ),
    ]
