# Generated by Django 6.0.5 on 2026-08-30 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0022_alter_piteventgradingconfig_panel_rubric_and_more'),
        ('grading', '0012_teamgrade_adviser_score_is_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgrade',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='revision_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='verdict',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('approved_with_revisions', 'Approved with Revisions'), ('for_redefense', 'For Re-defense')], max_length=30),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='verdict_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='verdict_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_verdicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='verdict_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GradeAttemptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('panel_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adviser_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('panel_weight', models.PositiveSmallIntegerField(default=50)),
                ('adviser_weight', models.PositiveSmallIntegerField(default=30)),
                ('peer_weight', models.PositiveSmallIntegerField(default=20)),
                ('verdict', models.CharField(blank=True, max_length=30)),
                ('verdict_remarks', models.TextField(blank=True)),
                ('verdict_at', models.DateTimeField(blank=True, null=True)),
                ('revision_deadline', models.DateField(blank=True, null=True)),
                ('snapshotted_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, help_text='The defense schedule this attempt was graded under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_grade_snapshots', to='defense.defenseschedule')),
                ('snapshotted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshotted_grades', to=settings.AUTH_USER_MODEL)),
                ('team_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to='grading.teamgrade')),
                ('verdict_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdict_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_center_gradeattempthistory',
                'ordering': ['attempt_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('team_grade', 'attempt_number'), name='unique_attempt_per_grade')],
            },
        ),
    ]
