# Generated by Django 6.0.5 on 2026-09-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_teamgrade_attempt_count_teamgrade_revision_deadline_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rubric',
            table='rubrics',
        ),
        migrations.AlterModelTable(
            name='rubriccriterion',
            table='rubric_criteria',
        ),
    ]
