# Generated by Django 6.0.5 on 2026-10-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0015_panelistgradesubmission_is_void_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebreakdown',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradebreakdown',
            name='source_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_rows', to='grading.panelistgradesubmission'),
        ),
    ]
