# Generated by Django 6.0.5 on 2026-10-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period_management', '0005_semestertransitionlog'),
        ('defense', '0030_defenseschedule_project_title_snapshot_and_more'),
        ('grading', '0016_gradebreakdown_is_void_and_more'),
        ('student_teams', '0008_studentteam_unlocked_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamgrade',
            name='unique_capstone_grade_per_team_stage',
        ),
        migrations.RemoveConstraint(
            model_name='teamgrade',
            name='unique_pit_grade_per_team_event',
        ),
        migrations.AddField(
            model_name='gradeattempthistory',
            name='clearance_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gradeattempthistory',
            name='project_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gradeattempthistory',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gradeattempthistory',
            name='revisions_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='clearance_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='compliance_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='project_title_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='project_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='redefense_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='redefense_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='redefense_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_redefense_readiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='revisions_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgrade',
            name='revisions_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_defense_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamgrade',
            name='verdict',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('approved_with_revisions', 'Approved with Revisions'), ('for_redefense', 'For Re-defense'), ('failed', 'Failed'), ('project_rejected', 'Project Rejected')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='teamgrade',
            constraint=models.UniqueConstraint(condition=models.Q(('defense_stage__isnull', False), ('scope', 'capstone')), fields=('team', 'semester', 'scope', 'defense_stage', 'project_version'), name='unique_capstone_grade_per_team_stage'),
        ),
        migrations.AddConstraint(
            model_name='teamgrade',
            constraint=models.UniqueConstraint(condition=models.Q(('pit_event_config__isnull', False), ('scope', 'pit')), fields=('team', 'semester', 'scope', 'pit_event_config', 'project_version'), name='unique_pit_grade_per_team_event'),
        ),
    ]
