# Generated by Django 6.0.5 on 2026-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SECURITY', 'Account & Security'), ('MINUTES', 'Minutes & Signatures'), ('DEFENSE', 'Defense Schedule'), ('PEER_EVAL', 'Peer Evaluation'), ('ANNOUNCEMENT', 'System Announcement')], default='GENERAL', max_length=50),
        ),
    ]
